### ISSUE TITLE
Add support for generating caves

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/map#39]
This would most likely be ASCII representations of caves.

Tasks:
* [x] Identity a good noise library
* [x] Create a prototype app for it (see https://github.com/hexagram30/noise/issues/1)
* [x] Create a docker image for the app (see https://github.com/hexagram30/docker/issues/3 & https://github.com/hexagram30/docker/issues/4)
* [ ] Convert the app into a gRPC-based service
   * [ ] Consider running a gRPC service - https://github.com/hexagram30/noise/issues/2
   * [ ] Define gRPC-based execution flow - https://github.com/hexagram30/noise/issues/3
   * [ ] Implement gRPC service - https://github.com/hexagram30/noise/issues/4
   * [ ] Generate Go lib for noise service
* [ ] Update the CLI to generate caves - https://github.com/hexagram30/cli/issues/6
* [ ] Devise mechanism for assigning caves to geophysical location on map
   * With a pixel representing ~1000km<sup>2</sup>, many cave systems could fit on a pixel
   * Subpixel indexing will be needed, following on the Hilbert curve work being done in https://github.com/hexagram30/raster/issues/25
   * [ ] Provide a means of storing caves in the raster service's DB (see https://github.com/hexagram30/raster/issues/27)
* [ ] Support image-generation of cave raster data
* [ ] Support ASCII-generation of cave raster data
* [ ] Provide a means of linking generated caves in support of creating cave systems

**Comment by oubiwann** [comment]
Of all the open source noise-generator libraries I looked at (Go, Clojure, Haskell, Rust, Java, C, and C++ libs were all considered), the [Rust one](https://github.com/Razaekel/noise-rs) was the best-designed, cleanest code, and easiest to extend (without having to fork the repo). Very well-done software design; kudos to @Razaekel.
